#!/usr/bin/env bash
# lib/harbor_env.sh — env exports for harbor agent(§8) + environment backend(§7), branching by SCAFFOLD × BACKEND.
# Contract: runner first sets SCAFFOLD BACKEND REPO_ROOT project_name exp_name SERVED_MODEL_NAME
#       TOOL_PARSER max_prompt_length max_response_length temperature, then sources this.
# Output: a pile of HARBOR_*/K8S_*/DOCKER_* exports + AGENT_LOOP_CONFIG(path) + NUM_WORKERS.
# The "why" of each default is in the Troubleshooting section of the docs site; no more comment piles here.
# shellcheck disable=SC2086,SC1090,SC1091

SCAFFOLD="$(printf '%s' "${SCAFFOLD:-ohsdk}" | tr '[:upper:]' '[:lower:]')"
BACKEND="$(printf '%s' "${BACKEND:-k8s}" | tr '[:upper:]' '[:lower:]')"
_CFG_DIR="$REPO_ROOT/src/verl_patch/config"
export HARBOR_SERVED_MODEL_NAME="${SERVED_MODEL_NAME:-vllm_model}"

# ── §8a scaffold: agent class / runtime image / provider env / loop config ──
case "$SCAFFOLD" in
  ohsdk)  # OpenHands-SDK (primary). AGENT_NAME must be null → uses import_path=CustomOpenHandsSDK
    : "${HARBOR_AGENT_NAME:=null}"
    : "${HARBOR_AGENT_IMPORT_PATH:=harbor.agents.custom.openhands_sdk:CustomOpenHandsSDK}"
    : "${HARBOR_AGENT_RUNTIME_IMAGE:=docker.io/jierun/c-oh-sdk-1.33.0:v0.1}"
    : "${HARBOR_AGENT_RUNTIME_MOUNT_PATH:=/opt/custom-agent-runtime/oh-sdk}"
    : "${HARBOR_AGENT_RUNTIME_IMAGE_SUBPATH:=opt/custom-agent-runtime/oh-sdk}"
    : "${HARBOR_AGENT_VERSION:=1.33.0}"
    # NOTE: must be `export VAR="${VAR:-{...}}"`, NOT `: "${VAR:={...}}"` — the `:=` assign form
    # swallows the dict's own closing brace with literal braces in the default → oc.decode parse error.
    export HARBOR_AGENT_MODEL_INFO="${HARBOR_AGENT_MODEL_INFO:-{max_input_tokens: ${max_prompt_length:-40000}, max_output_tokens: ${max_response_length:-91072}, input_cost_per_token: 0, output_cost_per_token: 0}}"
    _loop_default="agent_loop_config_oh.yaml"; : "${ENABLE_R3:=True}" ;;
  oh)     # native openhands-ai (image-mounted). the old docker path defaults to this scaffold
    : "${HARBOR_AGENT_NAME:=null}"
    : "${HARBOR_AGENT_IMPORT_PATH:=harbor_patch.agents.image_mounted_openhands_ai.openhands:OpenHands}"
    : "${HARBOR_AGENT_RUNTIME_IMAGE:=yuantao428/harbor-openhands-ai-runtime:0.50.0}"
    : "${HARBOR_AGENT_RUNTIME_MOUNT_PATH:=/opt/custom-agent-runtime/openhands-ai}"
    : "${HARBOR_AGENT_RUNTIME_IMAGE_SUBPATH:=opt/custom-agent-runtime/openhands-ai}"
    : "${HARBOR_AGENT_VERSION:=0.50.0}"
    _loop_default="agent_loop_config_oh.yaml"; : "${ENABLE_R3:=True}" ;;
  cc)     # Claude Code. Anthropic Messages surface; base_url injected per-session by the loop
    : "${HARBOR_AGENT_NAME:=claude-code}"
    : "${HARBOR_AGENT_IMPORT_PATH:=harbor_patch.agents.image_mounted_claude_code:ClaudeCode}"
    : "${HARBOR_AGENT_RUNTIME_IMAGE:=docker.io/jierun/c-cc-2.1.118:v0.1}"
    : "${HARBOR_AGENT_RUNTIME_MOUNT_PATH:=/opt/custom-agent-runtime/claude-code}"
    : "${HARBOR_AGENT_RUNTIME_IMAGE_SUBPATH:=opt/custom-agent-runtime/claude-code}"
    : "${HARBOR_AGENT_VERSION:=2.1.118}"
    export HARBOR_ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-${HARBOR_ANTHROPIC_API_KEY:-sk-dummy}}"
    export HARBOR_ANTHROPIC_MODEL="${HARBOR_ANTHROPIC_MODEL:-${SERVED_MODEL_NAME:-vllm_model}}"
    _loop_default="agent_loop_config_cc.yaml"; : "${ENABLE_R3:=True}" ;;
  oc)     # OpenCode. OpenAI-compatible hosted_vllm; in-pod opencode config generated by the loop
    : "${HARBOR_AGENT_NAME:=opencode}"
    : "${HARBOR_AGENT_IMPORT_PATH:=harbor_patch.agents.image_mounted_opencode:OpenCode}"
    : "${HARBOR_AGENT_RUNTIME_IMAGE:=docker.io/jierun/c-oc-1.14.22:v0.1}"
    : "${HARBOR_AGENT_RUNTIME_MOUNT_PATH:=/opt/custom-agent-runtime/opencode}"
    : "${HARBOR_AGENT_RUNTIME_IMAGE_SUBPATH:=opt/custom-agent-runtime/opencode}"
    : "${HARBOR_AGENT_VERSION:=1.14.22}"
    export HARBOR_OPENAI_BASE_URL="${HARBOR_OPENAI_BASE_URL:-http://in-process-proxy/v1}"
    export HARBOR_OPENAI_API_KEY="${HARBOR_OPENAI_API_KEY:-sk-dummy}"
    export HARBOR_CUSTOM_AGENT_OPENCODE="${HARBOR_CUSTOM_AGENT_OPENCODE:-$HARBOR_AGENT_RUNTIME_MOUNT_PATH/bin/opencode}"
    export HARBOR_CUSTOM_AGENT_RUNTIME_ENV_SCRIPT="${HARBOR_CUSTOM_AGENT_RUNTIME_ENV_SCRIPT:-$HARBOR_AGENT_RUNTIME_MOUNT_PATH/runtime-env.sh}"
    _loop_default="agent_loop_config_oc.yaml"; : "${ENABLE_R3:=False}" ;;
  *) echo "[harbor_env][FATAL] unknown SCAFFOLD='$SCAFFOLD' (supports ohsdk|oh|cc|oc)" >&2; return 1 2>/dev/null || exit 1 ;;
esac
export HARBOR_AGENT_NAME HARBOR_AGENT_IMPORT_PATH HARBOR_AGENT_RUNTIME_IMAGE \
       HARBOR_AGENT_RUNTIME_MOUNT_PATH HARBOR_AGENT_RUNTIME_IMAGE_SUBPATH HARBOR_AGENT_VERSION ENABLE_R3
# tool_parser: this one variable drives both vLLM serving and agent-side parsing; must align with chat_template (oc uses in-pod config, doesn't have this)
[ "$SCAFFOLD" != "oc" ] && export HARBOR_TOOL_PARSER="${TOOL_PARSER:-${HARBOR_TOOL_PARSER:-qwen3_coder}}"
[ -n "${HARBOR_AGENT_MODEL_INFO:-}" ] && export HARBOR_AGENT_MODEL_INFO

# ── §8b common agent knobs (scaffold-set defaults above already take priority) ──
export HARBOR_AGENT_MAX_ITERATIONS="${HARBOR_AGENT_MAX_ITERATIONS:-200}"
export HARBOR_AGENT_MAX_TIMEOUT_SEC="${HARBOR_AGENT_MAX_TIMEOUT_SEC:-2400}"
export HARBOR_AGENT_OVERRIDE_TIMEOUT_SEC="${HARBOR_AGENT_OVERRIDE_TIMEOUT_SEC:-2400}"
export HARBOR_AGENT_DISABLE_TOOL_CALLS="${HARBOR_AGENT_DISABLE_TOOL_CALLS:-False}"
export HARBOR_AGENT_TEMPERATURE="${HARBOR_AGENT_TEMPERATURE:-${temperature:-1.0}}"
export HARBOR_MAX_CONSECUTIVE_NO_TOOL="${HARBOR_MAX_CONSECUTIVE_NO_TOOL:-3}"
export HARBOR_TRIALS_DIR="${HARBOR_TRIALS_DIR:-$REPO_ROOT/harbor_trials/${project_name:-proj}/${exp_name:-exp}}"
export HARBOR_MAX_RETRIES="${HARBOR_MAX_RETRIES:-2}"
export HARBOR_VERIFIER_ENABLED="${HARBOR_VERIFIER_ENABLED:-True}"
# val-specific timeout/retries (without them, val only evaluates ~170/500 each time)
export HARBOR_VAL_MAX_RETRIES="${HARBOR_VAL_MAX_RETRIES:-2}"
export HARBOR_VAL_AGENT_MAX_TIMEOUT_SEC="${VAL_TIMEOUT:-${HARBOR_VAL_AGENT_MAX_TIMEOUT_SEC:-4800}}"
export HARBOR_AGENT_SETUP_TIMEOUT_MULTIPLIER="${HARBOR_AGENT_SETUP_TIMEOUT_MULTIPLIER:-5.0}"
export HARBOR_AGENT_TIMEOUT_MULTIPLIER="${HARBOR_AGENT_TIMEOUT_MULTIPLIER:-1.0}"
export HARBOR_ENVIRONMENT_BUILD_TIMEOUT_MULTIPLIER="${HARBOR_ENVIRONMENT_BUILD_TIMEOUT_MULTIPLIER:-1.0}"
export HARBOR_VERIFIER_TIMEOUT_MULTIPLIER="${HARBOR_VERIFIER_TIMEOUT_MULTIPLIER:-1.0}"
export HARBOR_TAIL_KILL_TARGET="${HARBOR_TAIL_KILL_TARGET:-1.0}"
export HARBOR_TAIL_KILL_GRACE_SEC="${HARBOR_TAIL_KILL_GRACE_SEC:-180}"
export HARBOR_TAIL_KILL_MIN_TASKS="${HARBOR_TAIL_KILL_MIN_TASKS:-96}"

# ── §7 backend: environment backend (k8s pulls prebuilt images / docker remote daemon builds on the fly) ──
export HARBOR_ENVIRONMENT_TYPE="${HARBOR_ENVIRONMENT_TYPE:-null}"
export HARBOR_ENVIRONMENT_DELETE="${HARBOR_ENVIRONMENT_DELETE:-True}"
export HARBOR_ENVIRONMENT_OVERRIDE_CPUS="${HARBOR_ENVIRONMENT_OVERRIDE_CPUS:-1}"
case "$BACKEND" in
  k8s)
    : "${HARBOR_ENVIRONMENT_IMPORT_PATH:=harbor_patch.environments.kubernetes.kubernetes:KubernetesEnvironment}"
    export HARBOR_ENVIRONMENT_IMPORT_PATH
    export HARBOR_ENVIRONMENT_FORCE_BUILD="${HARBOR_ENVIRONMENT_FORCE_BUILD:-False}"
    export HARBOR_ENVIRONMENT_OVERRIDE_MEMORY_MB="${HARBOR_ENVIRONMENT_OVERRIDE_MEMORY_MB:-4096}"
    # kubeconfig: default is the k8s standard path; local cluster path goes in site.env (preflight validates existence)
    K8S_KUBECONFIG="${K8S_KUBECONFIG:-${KUBECONFIG:-$HOME/.kube/config}}"
    export K8S_KUBECONFIG KUBECONFIG="$K8S_KUBECONFIG"
    export K8S_NAMESPACE="${K8S_NAMESPACE:-default}"
    export K8S_POD_STARTUP_TIMEOUT="${K8S_POD_STARTUP_TIMEOUT:-1200}"
    export K8S_POD_ACTIVE_DEADLINE_SECONDS="${K8S_POD_ACTIVE_DEADLINE_SECONDS:-6000}"
    export K8S_VAL_POD_STARTUP_TIMEOUT="${K8S_VAL_POD_STARTUP_TIMEOUT:-2400}"
    export K8S_VAL_POD_ACTIVE_DEADLINE_SECONDS="${K8S_VAL_POD_ACTIVE_DEADLINE_SECONDS:-7200}"
    # ── prebuilt-image "acceleration" = site-specific (many clusters lack it). Defaults to portable inline-build. ──
    # registry non-empty (site set it) → pull <reg>/openswe-<id> for instant start; empty → generic inline-build. Mutually exclusive, preflight validates.
    export HARBOR_OPENSWE_IMAGE_REGISTRY="${IMAGE_REGISTRY-${HARBOR_OPENSWE_IMAGE_REGISTRY-}}"
    export HARBOR_NYDUS_MIRROR="${NYDUS_MIRROR-${HARBOR_NYDUS_MIRROR-}}"   # empty = don't rewrite swebench images
    if [ -n "$HARBOR_OPENSWE_IMAGE_REGISTRY" ]; then    # site has prebuilt images
        export HARBOR_K8S_INLINE_BUILD="${INLINE_BUILD:-${HARBOR_K8S_INLINE_BUILD:-false}}"
        export HARBOR_OPENSWE_SKIP_DOCKERFILE="${HARBOR_OPENSWE_SKIP_DOCKERFILE:-true}"
    else                                                # vanilla: build in-pod on the fly
        export HARBOR_K8S_INLINE_BUILD="${INLINE_BUILD:-${HARBOR_K8S_INLINE_BUILD:-true}}"
        export HARBOR_OPENSWE_SKIP_DOCKERFILE="${HARBOR_OPENSWE_SKIP_DOCKERFILE:-false}"
    fi
    # pod memory LIMIT = request×FACTOR (stops a runaway pod from blowing up the node → node lost → training deadlock). Portable default, kept.
    export HARBOR_ENVIRONMENT_MEMORY_LIMIT_FACTOR="${HARBOR_ENVIRONMENT_MEMORY_LIMIT_FACTOR:-4}"
    # hostPath mounts (rebench log parsing / grading toolchain) = site-specific. Default null (no mounts).
    export HARBOR_HOSTPATH_MOUNTS="${HARBOR_HOSTPATH_MOUNTS:-null}"
    export HARBOR_POD_NAME_PREFIX="${POD_NAME_PREFIX:-${HARBOR_POD_NAME_PREFIX:-harbor-$SCAFFOLD}}"
    ;;
  docker)
    : "${HARBOR_ENVIRONMENT_IMPORT_PATH:=harbor_patch.environments.remote_docker:RemoteDockerEnvironment}"
    export HARBOR_ENVIRONMENT_IMPORT_PATH
    export HARBOR_ENVIRONMENT_FORCE_BUILD="${HARBOR_ENVIRONMENT_FORCE_BUILD:-True}"   # remote daemon builds task images on the fly
    export DOCKER_HOST="${DOCKER_HOST:-tcp://YOUR_DOCKER_HOST:2375}"
    export HARBOR_ENVIRONMENT_OVERRIDE_MEMORY_MB="${HARBOR_ENVIRONMENT_OVERRIDE_MEMORY_MB:-8192}"
    ;;
  *) echo "[harbor_env][FATAL] unknown BACKEND='$BACKEND' (supports k8s|docker)" >&2; return 1 2>/dev/null || exit 1 ;;
esac

# ── agent_loop_config resolution: docker currently has only one oh_docker; otherwise by scaffold ──
if [ "$BACKEND" = "docker" ]; then
    AGENT_LOOP_CONFIG="${AGENT_LOOP_CONFIG:-$_CFG_DIR/agent_loop_config_oh_docker.yaml}"
else
    AGENT_LOOP_CONFIG="${AGENT_LOOP_CONFIG:-$_CFG_DIR/$_loop_default}"
fi
export AGENT_LOOP_CONFIG
export NUM_WORKERS="${NUM_WORKERS:-96}"
