#!/usr/bin/env python3
"""Bake the task image's own ENV into tests/image_env.sh and source it from tests/test.sh.

Why: the Kubernetes backend (src/harbor_patch/environments/kubernetes/kubernetes.py) sets its
own PATH on the pod spec, which REPLACES the image's `ENV PATH` for every exec. The agent
survives (its shell is a login shell that sources /root/.cargo/env & co.), but the verifier runs
`bash /tests/test.sh` non-login and loses every toolchain the image only exposes through ENV:
2026-09-07 tokio-rs__axum-691 scored a false 0 with `cargo: command not found` (image PATH is
/usr/local/cargo/bin:..., CARGO_HOME=/usr/local/cargo). Same class as the `_persist_inline_build_env`
fix in kubernetes.py, which only covers skip-dockerfile / inline-build mode, not the legacy mode
these datasets run in.

Fix: read the image config from a registry (the local 222 mirror first, docker.io second), write
its Env as `export` lines (PATH is PREPENDED to the pod's PATH so /opt/grading & co. stay
reachable), and make test.sh source the file right after its shebang. Idempotent; safe to run on
a dataset that is being evaluated (harbor uploads tests/ when the verifier starts).

    python utils/harbor_image_env.py /path/to/data/harbor_swebench_multilingual_300 [more dirs] \
        [--registry 127.0.0.1:5001] [--workers 16] [--force]
"""
from __future__ import annotations

import argparse
import base64
import json
import os
import re
import shlex
import sys
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

ACCEPT = ("application/vnd.oci.image.index.v1+json, application/vnd.docker.distribution.manifest.list.v2+json, "
          "application/vnd.docker.distribution.manifest.v2+json, application/vnd.oci.image.manifest.v1+json")
SOURCE_LINE = '[ -f /tests/image_env.sh ] && . /tests/image_env.sh  # image ENV (pod overrides PATH); see utils/harbor_image_env.py'
SKIP_KEYS = {"TMPDIR", "HOSTNAME", "HOME"}


def _get(url: str, headers: dict, timeout: int = 60) -> tuple[bytes, dict]:
    r = urllib.request.urlopen(urllib.request.Request(url, headers=headers), timeout=timeout)
    return r.read(), dict(r.headers)


def _hub_token(repo: str) -> str:
    hdr = {}
    try:
        cfg = json.load(open(os.path.expanduser("~/.docker/config.json")))
        auth = cfg.get("auths", {}).get("https://index.docker.io/v1/", {}).get("auth")
        if auth:
            hdr["Authorization"] = f"Basic {auth}"
    except Exception:  # noqa: BLE001
        pass
    body, _ = _get(f"https://auth.docker.io/token?service=registry.docker.io&scope=repository:{repo}:pull", hdr)
    return json.loads(body)["token"]


def image_config(image: str, registry: str | None) -> dict:
    """Return the OCI image config (the JSON with .config.Env) for `image`, linux/amd64."""
    ref = image.removeprefix("docker.io/")
    if "@" in ref:                      # digest ref: repo@sha256:<hex>
        repo, _, tag = ref.partition("@")
    else:
        repo, sep, tag = ref.rpartition(":")
        if not sep or "/" in tag:       # "ubuntu" / "owner/name" -- no tag at all
            repo, tag = ref, "latest"
    # Docker Hub requires the library/ prefix for official single-component images; a local
    # mirror keeps whatever name it was pushed under.
    hub_repo = repo if "/" in repo else f"library/{repo}"
    attempts = []
    if registry:
        attempts.append((f"http://{registry}/v2/{repo}", {"Accept": ACCEPT}))
    attempts.append((f"https://registry-1.docker.io/v2/{hub_repo}", None))  # token fetched lazily
    last = None
    for base, hdr in attempts:
        try:
            if hdr is None:
                hdr = {"Accept": ACCEPT, "Authorization": f"Bearer {_hub_token(hub_repo)}"}
            body, _ = _get(f"{base}/manifests/{tag}", hdr)
            m = json.loads(body)
            if "manifests" in m:
                cands = [x for x in m["manifests"]
                         if (x.get("platform") or {}).get("architecture") == "amd64"
                         and not (x.get("annotations") or {}).get("vnd.docker.reference.type")]
                if not cands:
                    raise RuntimeError("no linux/amd64 manifest in index")
                body, _ = _get(f"{base}/manifests/{cands[0]['digest']}", hdr)
                m = json.loads(body)
            body, _ = _get(f"{base}/blobs/{m['config']['digest']}", hdr)
            return json.loads(body)
        except Exception as e:  # noqa: BLE001
            last = e
            continue
    raise RuntimeError(f"could not fetch image config for {image}: {last}")


def render_env_sh(image: str, env: list[str]) -> str:
    lines = ["#!/bin/bash",
             f"# ENV of {image} (image config), replayed because the k8s pod spec overrides PATH.",
             "# Generated by utils/harbor_image_env.py; sourced by tests/test.sh."]
    for e in env:
        k, _, v = e.partition("=")
        if not k or k in SKIP_KEYS:
            continue
        if k == "PATH":
            lines.append(f'export PATH={shlex.quote(v)}":$PATH"')
        else:
            lines.append(f"export {k}={shlex.quote(v)}")
    return "\n".join(lines) + "\n"


def patch_test_sh(test_sh: Path) -> bool:
    s = test_sh.read_text()
    if SOURCE_LINE in s:
        return False
    lines = s.split("\n")
    # insert after the shebang and the canary comment line(s) that follow it
    i = 1 if lines and lines[0].startswith("#!") else 0
    while i < len(lines) and lines[i].startswith("#"):
        i += 1
    lines.insert(i, SOURCE_LINE)
    test_sh.write_text("\n".join(lines))
    return True


def process_task(task_dir: Path, registry: str | None, force: bool) -> str:
    toml = (task_dir / "task.toml")
    m = re.search(r'^docker_image = "(.*)"', toml.read_text(), re.M) if toml.exists() else None
    if not m:
        return "SKIP(no docker_image)"
    image = m.group(1)
    out = task_dir / "tests" / "image_env.sh"
    if out.exists() and not force:
        patched = patch_test_sh(task_dir / "tests" / "test.sh")
        return "OK(kept)" + ("+patched" if patched else "")
    cfg = image_config(image, registry)
    env = (cfg.get("config") or {}).get("Env") or []
    out.write_text(render_env_sh(image, env))
    out.chmod(0o755)
    (task_dir / "tests" / "image_env.json").write_text(json.dumps(
        {"image": image, "Env": env, "WorkingDir": (cfg.get("config") or {}).get("WorkingDir")}, indent=2))
    patched = patch_test_sh(task_dir / "tests" / "test.sh")
    return "OK" + ("+patched" if patched else "")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("dataset_dirs", nargs="+", type=Path)
    ap.add_argument("--registry", default="127.0.0.1:5001", help="local mirror to read image configs from ('' = docker.io only)")
    ap.add_argument("--workers", type=int, default=16)
    ap.add_argument("--force", action="store_true", help="re-fetch even if tests/image_env.sh exists")
    args = ap.parse_args()
    tasks = [d for ds in args.dataset_dirs for d in sorted(ds.iterdir()) if (d / "task.toml").exists()]
    print(f"{len(tasks)} tasks")
    results: dict[str, int] = {}
    failures = []
    with ThreadPoolExecutor(args.workers) as ex:
        for task, res in zip(tasks, ex.map(lambda t: _safe(t, args.registry or None, args.force), tasks)):
            results[res.split("(")[0]] = results.get(res.split("(")[0], 0) + 1
            if res.startswith("FAIL"):
                failures.append((task.name, res))
    print(results)
    for n, r in failures[:20]:
        print("  ", n, r)
    sys.exit(1 if failures else 0)


def _safe(task: Path, registry: str | None, force: bool) -> str:
    try:
        return process_task(task, registry, force)
    except Exception as e:  # noqa: BLE001
        return f"FAIL({type(e).__name__}: {e})"


if __name__ == "__main__":
    main()
